export const Users = [
    {
      id:1,
      profilePicture: "asset/personas/rafa.png",
      username: "Rafael Fajardo",
    },
    {
      id:2,
      profilePicture: "asset/personas/mni.png",
      username: "Monica Angulo",
    },
    {
      id:3,
      profilePicture: "asset/personas/mauricio.png",
      username: "Mauricio Ruiz",
    },
    {
      id:4,
      profilePicture: "asset/personas/jose.png",
      username: "Jose Rassa",
    },
    {
      id:5,
      profilePicture: "asset/personas/edgar.png",
      username: "Edgar Orozco",
    },
    {
      id:6,
      profilePicture: "asset/personas/rafa.png",
      username: "Shirley Beauchamp",
    },
    {
      id:7,
      profilePicture: "asset/personas/rafa.png",
      username: "Travis Bennett",
    },
    {
      id:8,
      profilePicture: "asset/personas/rafa.png",
      username: "Kristen Thomas",
    },
    {
      id:9,
      profilePicture: "asset/personas/rafa.png",
      username: "Gary Duty",
    },
    {
      id:10,
      profilePicture: "asset/personas/rafa.png",
      username: "Safak Kocaoglu",
    },
  ];
  
  export const Posts = [
    {
      id: 1,
      desc: '" Para iniciar el día toma una buen tasa de café ...Y tendrás un excelente día."',
      photo: "asset/post/1.jpeg",
      date: "hace 5 minutos",
      userId: 1,
      like: 32,
      comment: 9,
    },
    {
      id: 2,
      desc: '"Amigos y café, la mejor combinación."',
      photo: "asset/post/2.jpeg",
      date: "hace 15 minutos",
      userId: 2,
      like: 2,
      comment: 1,
    },
    {
      id: 3,
      desc: '"Cafe, el origen y combustible de grandes proyectos."',
      photo: "asset/post/3.jpeg",
      date: "hace 1 hora",
      userId: 3,
      like: 61,
      comment: 2,
    },
    {
      id: 4,
      desc: '"La felicidad es un buen libro y una taza de café."',
      photo: "asset/post/4.jpeg",
      date: "hace 4 horas",
      userId: 4,
      like: 7,
      comment: 3,
    },
    {
      id: 5,
      desc:'"En cada sorbo de café hay una buena idea escondida."',
      photo: "asset/post/5.jpeg",
      date: "hace 5 horas",
      userId: 5,
      like: 23,
      comment: 5,
    },
    {
      id: 6,
      photo: "asset/post/1.jpeg",
      date: "Hace 1 día",
      userId: 6,
      like: 44,
      comment: 6,
    },
    {
      id: 7,
      desc: "Never regret anything that made you smile.",
      photo: "asset/post/2.jpeg",
      date: "Hace 2 día",
      userId: 7,
      like: 52,
      comment: 3,
    },
    {
      id: 8,
      photo: "asset/post/3.jpeg",
      date: "Hace 3 día",
      userId: 8,
      like: 15,
      comment: 1,
    },
    {
      id: 9,
      desc: "Change the world by being yourself.",
      photo: "asset/post/4.jpeg",
      date: "Hace 5 día",
      userId: 9,
      like: 11,
      comment: 2,
    },
    {
      id: 10,
      photo: "asset/post/5.jpeg",
      date: "1 week ago",
      userId: 10,
      like: 104,
      comment: 12,
    },
  ];